### ISSUE TITLE
package download issues?

### ISSUE THREAD

**Issue by lcc2207** [opscode-cookbooks/push-jobs#17]
Is anyone else having issues getting this cookbook to download the package?

**Comment by cfoutsgit** [comment]
What kind of issues are you having? I had issues downloading them because the download pages show the sha1 checksum, but my nodes required the sha256sum checksum

**Comment by fog1985** [comment]
Hi. 
Issue is already resolved.  But issues was in the fact that cookbook is expecting SHA256 checksum for package.  But on a site form Chef where we download package for push-jobs client checksum is mentioned in SH1. Hence I had to download package, get SHA256 out of it, put it into push-jobs cookbook and only then it worked. 
So just mismatch between what is provided on Chef  site and what is expected within cookbook. 
Regards, Taras. 

05 лютого 2015, 15:37:21, від cfoutsgit < notifications@github.com >: 

What kind of issues are you having? I had issues downloading them because the download pages show the sha1 checksum, but my nodes required the sha256sum checksum —

**Comment by jtimberman** [comment]
Yeah, this is definitely sub-optimal. We have an issue in the backlog to get SHA256 checksums on the downloads page, but there's some other work ahead of that.
